# Generated by Django 5.2.1 on 2025-06-11 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='product_id',
        ),
    ]
