# Generated by Django 5.2.1 on 2025-06-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_product_order_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
    ]
