# Generated by Django 5.2.1 on 2025-06-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_productsize_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetypes',
            name='description',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
    ]
