# Generated by Django 5.2.1 on 2025-06-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_pricetypes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetypes',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
