# Generated by Django 5.2.1 on 2025-07-09 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_stripelogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripelogs',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stripe_logs', to='store.order'),
        ),
    ]
