# Generated by Django 5.2.1 on 2025-07-10 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_coinbaselogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinbaselogs',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coinbase_logs', to='store.order'),
        ),
    ]
