# Generated by Django 5.2.1 on 2025-08-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_orderitem_price_at_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='personalized',
            field=models.BooleanField(default=False),
        ),
    ]
