# Generated by Django 5.2.1 on 2025-08-31 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_personalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='personalized',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
    ]
