# Generated by Django 5.2.1 on 2025-09-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_orderitem_personalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
