# Generated by Django 5.2.1 on 2025-09-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_product_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='return_items',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
