# Generated by Django 5.2.1 on 2025-09-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_remove_order_quantity_order_city_order_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company_address',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='company_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='company_city',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='company_postal_code',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
