# Generated by Django 5.2.1 on 2025-09-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_order_company_address_order_company_check_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='postal_number',
            new_name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
