# Generated by Django 5.2.1 on 2025-09-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_rename_postal_number_order_postal_code_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='company_postal_code',
            field=models.TextField(blank=True, default='', max_length=10, null=True),
        ),
    ]
