# Generated by Django 5.2.1 on 2025-09-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_orderitem_price_tax_alter_order_company_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='price_tax',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
