# Generated by Django 5.2.1 on 2025-10-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='settings',
            field=models.BooleanField(default=False),
        ),
    ]
