# Generated by Django 5.2.1 on 2025-10-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_product_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='settings',
            field=models.BooleanField(default=False),
        ),
    ]
