# Generated by Django 5.2.1 on 2025-10-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_productprice_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='settings',
        ),
        migrations.AddField(
            model_name='pricetypes',
            name='settings',
            field=models.BooleanField(default=False),
        ),
    ]
