# Generated by Django 5.2.1 on 2025-12-03 13:02

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_create_default_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='uploads/product_gallery/', verbose_name='Slika'),
        ),
    ]
