# Generated by Django 5.2.1 on 2025-12-03 22:00

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='uploads/product/', verbose_name='Slika'),
        ),
    ]
