# Generated by Django 5.2.1 on 2025-12-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_alter_orderitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
    ]
