# Generated by Django 5.2.1 on 2025-12-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
