# Generated by Django 5.2.1 on 2025-12-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_productprice_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetypes',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
