# Generated by Django 5.2.1 on 2026-02-05 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0043_alter_orderitem_size"),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_type",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "delivery_id",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "delivery_name",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "delivery_address",
                    models.TextField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="store.order",
                    ),
                ),
            ],
        ),
    ]
