"""
Django settings for spletka project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ylu!!)q^bq&nq@)&3)(qpv&_(xoj!yxd*0$)2fl$b-g&#sq#5('

STRIPE_SECRET_KEY = "sk_test_51RhZ7GQILlH3U32jyqbbKE2jpLY3dTToCxbNc036kT5iNuiAbyhmUX7zbABbUEAFpiiRmsc2S8Uxd910WqhB14P000EBSCmkAQ"  # iz Stripe Dashboard
STRIPE_PUBLISHABLE_KEY = "pk_test_51RhZ7GQILlH3U32jLvpI5ZDdNSHZlbmKEZIPTRKZsXZBNYhc6IMozRkeVrdALvq7BwJhARjZrAb2rBzGM8T68AiE00fyDExrCE"
STRIPE_WEBHOOK_SECRET = 'whsec_3247759521c4baccc1db2124f1180a990797281accd7bdd53bf303f8dbb511db' #to je treba zamenjati, ko gremo v prod
COINBASE_API_KEY = 'c2354d2d-233e-4747-87f0-ae9316c70513'
COINBASE_WEBHOOK_SECRET = 'f50a497e-8af6-4ca7-ab4e-9a259688d078'
DOMAIN = "http://localhost:8000"  # pozneje spremeni na https://sentjur-metropola.si

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.ngrok-free.app', 'sentjur-metropola.si', 'www.sentjur-metropola.si']

CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok-free.app",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'spletka',
    'store',
    'accounts',
    'zajebancija',
    'widget_tweaks',
]
LOGIN_REDIRECT_URL = '/profile/'     # ali karkoli
LOGOUT_REDIRECT_URL = '/accounts/login/'
LOGIN_URL = '/accounts/login/'       # pot do login page
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'spletka.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'spletka', 'templates'),
                os.path.join(BASE_DIR, 'accounts', 'templates'),
                 os.path.join(BASE_DIR, 'zajebancija', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {

            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processors.cart_item_count',

            ],
        },
    },
]

WSGI_APPLICATION = 'spletka.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
