# Generated by Django 5.2.1 on 2025-06-24 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spletka', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='idea_text',
            new_name='idea',
        ),
    ]
