# Generated by Django 5.2.1 on 2025-07-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spletka', '0002_rename_idea_text_idea_idea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('preview_token', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
